library(tidyverse)
library(egg) # package for nice grids of plots, uses ggarrange

# clean up
rm(list=ls())

# set working directory to be where this file lives
# works with "source" using  BBedit or Rstudio,
# but not with "Run" in Rstudio and not with Rscript from the terminal.
script.dir <- dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Nice-ish y axis labels with ggplot
# Converts 1e6 into 10^6 etc., and avoids things like 1.5 x 10^-1 or 10^0
# Easiest to see with example:
# library(ggplot2)
# p=ggplot() + xlim(0,1)+ scale_y_continuous(limits=c(8e-4, 2e5),  trans="log10",
#         breaks = as.numeric(c(1,5) %o% 10^(-8:8)), minor_breaks = as.numeric(1:10 %o% 10^(-8:8)),
#   labels = ggplot_scientific_notation_axes_labels)

ggplot_scientific_notation_axes_labels <- function(l) {
  # 'prettyNum' puts things into scientific notation when digit strings get past a certain length,
  # but keeps things  >0.0001 and < 10^7 in non-sci notation
  l <- prettyNum(l)
  # … but for axis labels, we want to switch to powers of 10 for anything >=10^3 or < 0.01
  # (though you decide)
  for(i in 1:length(l)){
    number=eval(parse(text=l)[i])
    if(!is.na(number) & (number<0.01 | number>=1000)) l[i]=format(number, scientific=TRUE)
  }
  # quote the part before the exponent to keep all the digits
  l <- gsub("^(.*)e", "'\\1'e", l)
  # remove + after exponent, if exists. E.g.: (e^+2 -> e^2)
  l <- gsub("e\\+","e",l)  
  l <- gsub("e0","e",l)  
  l <- gsub("e-0","e-",l) 
  # turn the 'e' into plotmath format
  l <- gsub("e", "%*%10^", l)
  # convert 1x10^ or 1.000x10^ -> 10^
  l <- gsub("\\'1[\\.0]*\\'\\%\\*\\%", "", l)
  # convert 0x10^x to 0
  l <- gsub("\\'0[\\.0]*\\'\\%\\*\\%", "", l)
  l=gsub("10\\^0", "0", l)
  # return this as an expression
  parse(text=l)
}

labelsize=6
axistextsize=6
pointsize=0.5
# use this to snug up the plots by remving y axis labels
# obvs you then have to put info in the plot title
my_theme_tweaks=  theme(axis.text.x = element_text(size=labelsize),
                 axis.text.y = element_text(size=labelsize),
                 plot.title = element_text(size=labelsize,face="bold"),
                 axis.title.x= element_text(size=axistextsize),
                 axis.title.y= element_blank(),
                 legend.text=element_text(size=labelsize),
                 plot.margin = unit(c(0.2,0.2,0.2,0.2), 'lines'),
                 panel.grid.minor = element_line(linewidth = 0.2),
                 panel.grid.major = element_line(linewidth = 0.35))

# normal theme with y axis labels (what we use in this example)
my_theme_tweaks=  theme(axis.text.x = element_text(size=labelsize),
                      axis.text.y = element_text(size=labelsize),
                      plot.title = element_text(size=labelsize,face="bold"),
                      axis.title.x= element_text(size=axistextsize),
                      axis.title.y= element_text(size=axistextsize),
                      legend.text=element_text(size=labelsize),
                      plot.margin = unit(c(0.2,0.2,0.2,0.2), 'lines'),
                      panel.grid.minor = element_line(linewidth = 0.2),
                      panel.grid.major = element_line(linewidth = 0.35))


##########################################
# make five random datasets to plot and arrange in 2 rows
# we want to align the frames of each plot
# notice how we implement nice log scale labels/ticks/grid lines in plots 1 and 5
# plot #6 is generated by ggarrange and is blank - fills up the bottom row. 
# the call to ggarrange tells you this

tp=seq(0,20,1)
d=data.frame(times=tp, y1=2^tp, y2=tp, y3=tp^3 + 10, y4=1-exp(-0.3*tp), y5=2^(-tp))

p1=ggplot(d, aes(x=times, y=y1)) +  theme_bw() +
  scale_y_continuous(limits=c(1, 2e6),
                     trans="log10",
                     breaks = as.numeric(1 %o% 10^(0:6)), minor_breaks = as.numeric(1:10 %o% 10^(0:6)),
                     labels = ggplot_scientific_notation_axes_labels) + 
  geom_point(size=pointsize) + my_theme_tweaks + 
  ggtitle("Plot 1") +
  xlab("Time post-treatment") + ylab("Cell numbers") 
  
p2=ggplot(d, aes(x=times, y=y2)) + geom_point(size=pointsize) + ggtitle("Plot 2") + theme_bw() +
  xlab("Time post-treatment") + ylab("Whatever")+ my_theme_tweaks 

p3=ggplot(d, aes(x=times, y=y3)) + geom_point(size=pointsize) + ggtitle("Plot 3") + theme_bw() +
  xlab("Time post-treatment") + ylab("Cell numbers") + theme_bw()+ my_theme_tweaks 

p4=ggplot(d, aes(x=times, y=y4)) + geom_line() + ggtitle("Plot 4") + 
  xlab("Time post-treatment") + ylab("Frequency") + theme_bw() + my_theme_tweaks

# this one looks a bit weird as minor breaks are at 3 * 10^x, but there are no labels there
# so you don't know what those lines mean. But I did this to stop the axis labels being too tight
# probably better to have no minor breaks (minor_breaks = NULL  below)
# remember "breaks" are where the numbers are... 
p5 = ggplot(d, aes(x=times, y=y5)) + theme_bw() + my_theme_tweaks + 
  scale_y_continuous(limits=c(3e-7, 1),
                     trans="log10",
                     breaks = as.numeric(1 %o% 10^(-7:0)), minor_breaks = as.numeric(c(1,3) %o% 10^(-7:0)),
                     labels = ggplot_scientific_notation_axes_labels) + 
  geom_point(colour="orange",size=pointsize) + 
  ggtitle("Plot 5") +   xlab("Time post-treatment") + ylab("Frequency") + 
  theme_bw()+ my_theme_tweaks 

gc()  # garbage collection
# this may give obscure warning messages – you can usually ignore them 
# "draw=F" means we just build the object but don't plot it yet
p.egg=ggarrange(plots=list(p1,p2,p3,p4,p5), nrow=2, draw=F)                                                          

# this object is agnostic to the entire plot size, but the text labels in the PDF will
# be the actual size you specify. (so if you make the PDF too small, the text will look huge)
# Full width of page is about 6.5 inches. Fiddle with the PDF height to get the aspect ratios right
# We want each panel's aspect to be about the golden ratio, 1:1.6.
# takes bit of trial and error with the plot height

pdf("plots.egg.pdf", width=6.5, height=3.5)
print(p.egg)
dev.off()

# you can save space by removing y axis labels
# re-comment the "my_theme_tweaks" lines above to see what this looks like


